name: Alpha clean-up

on:
  # Check for updates every day
  # Allow to clean-up a specific version
  workflow_dispatch:
    inputs:
      appVersion:
        description: "The version to purge."
        required: true
        default: ""
jobs:
  alpha-cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.DEV_TOOLS_BASTION_PRIVATE_KEY }}
      - name: Clean-up old versions
        run: cleanup.sh
