on:
  workflow_dispatch

jobs:
  prepare-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: prepare matrix
        id: set-matrix
        run: |
          testresult=$(cat testresults.txt)
          matrix=$( echo "$testresult"|jq -R 'capture("(?<targets>@here) :(?<alert>.*?): <(?<url>[^ ]+)> (?<title>.*) :[^w]+ (?<duration>.*)")' | jq -sc )
          echo "matrix=$matrix" >> $GITHUB_OUTPUT        
  create-matrix:
    needs: prepare-matrix
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tickets: ${{ fromJson(needs.prepare-matrix.outputs.matrix) }}
    steps:
      - name: Send a slack message
        uses: slackapi/slack-github-action@e28cf165c92ffef168d23c5c9000cffc8a25e117
        with:
          payload: |
            {
              "blocks": [
                {
                  "type": "context",
                  "elements": [
                    {
                      "type": "image",
                      "image_url": "https://avatars.githubusercontent.com/u/460607?s=48&v=4",
                      "alt_text": "Nuxeo Support"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "@here **Nuxeo Suport breachwatcher**"
                    }
                  ]
                },
                {
                  "type": "divider"
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": ":alert: Ticket https://jira.nuxeo.com/browse/SUPNXP-48900|SUPNXP-48900|Config NUXEO - Recommandation> approaching breach in [03h40m] !"
                  }
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
