on:
    workflow_dispatch

jobs:
  prepare-matrix:
    runs-on: ubuntu-latest
    outputs:
        matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: prepare matrix
        id: set-matrix
        run: |
          notifsList="testresults.txt"
          notifs_length=$(cat testresults.txt | wc -l|tee total_result.txt)
          echo "$( cat total_result.txt|wc -l )"
          echo "matrix=$(cat testresults.txt | jq -cRs 'split("\n")[:-1]' )" >> $GITHUB_OUTPUT          
  create-matrix:
    needs: prepare-matrix
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tickets: ${{ fromJson(needs.prepare-matrix.outputs.matrix) }}
    container:
      image: node:20.3-alpine3.17
      # credentials:
      #   username:
      #   password:
      env:
        API_URL: some-url.com
      ports:
        - 80
    steps:
      - run: |
          echo "Dynamic value: ${{ matrix.tickets }}"
      - name: Send a slack message
        uses: docker://technosophos/slack-notify
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_TITLE: From Github Actions
          SLACK_MESSAGE: ${{ matrix.tickets }}
          SLACK_COLOR: "#723fc4"
  
  
