on:
  workflow_dispatch

jobs:
  prepare-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: prepare matrix
        id: set-matrix
        run: |
          testresult=$(cat testresults.txt)
          matrix=$( echo "$testresult"|jq -R '[capture("(?<notifer>@here) :(?<alert>.*?): <(?<url>[^ ]+)> (?<title>.*) :[^w]+ (?<duration>.*)")]'|jq -cs )
          echo "matrix=$matrix" >> $GITHUB_OUTPUT
        
  create-matrix:
    needs: prepare-matrix
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tickets: ${{ needs.prepare-matrix.outputs.matrix }}
    container:
      image: node:20.3-alpine3.17
    # credentials:
    #   username:
    #   password:
      env:
        API_URL: some-url.com
      ports:
        - 80
    steps:
      - name: Print Matrix Elements
        run: |
          for tickets in "${{ matrix.tickets }}"; do
            notifer=$(echo "$config" | jq -r '.notifer')
            alert=$(echo "$config" | jq -r '.alert')
            url=$(echo "$config" | jq -r '.url')
            title=$(echo "$config" | jq -r '.title')
            duration=$(echo "$config" | jq -r '.duration')
            echo "Notifer: $notifer, Alert: $alert, URL: $url, Title: $title, Duration: $duration"
          done
      - name: Send a slack message
        uses: docker://technosophos/slack-notify
        with:
          # For posting a rich message using Block Kit
          payload: |
            {
              "blocks": [
                 {
                   ${{ matrix.tickets }}  
                 }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
