# Workflow for BreachWatcher.
name: BreachWatcher Workflow

on:
  workflow_dispatch:
    inputs:
      silent_mode:
        description: silent_mode to supress verbosity, when installing packages
        type: boolean
        default: true
        required: true
      jira_host:
        description: Jira instance where to fetch ticket details
        default: jira.nuxeo.com
        required: true
      slack_channel:
        description: Slack channel where to send notification
        default: C06AG4TUBRB
        required: true
      branch:
        description: branch name
        default: master
        required: true
      ticketsResults:
        description: random ticket details for testing purpose
        required: false

  # Check for run every hour every day
 # schedule:
    # Everyday at every hour.
#    - cron: '20 0-23/1 * * *'

jobs:
  prepare-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.create-ticket-matrix.outputs.matrix }}
    env:
      SILENT_MODE: ${{ github.event.inputs.silent_mode }}
      JIRA_HOST: ${{ github.event.inputs.jira_host }}
      SLACK_CHANNEL: ${{ github.event.inputs.slack_channel }}
      BRANCH: ${{ github.event.inputs.branch }}
      JIRA_USERNAME: ${{ secrets.JIRA_USERNAME }}
      JIRA_PASSWORD: ${{ secrets.JIRA_PASSWORD }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x
                
      - name: Get Ticket Details
        id: get-tickets
        run: |
          ticketsResults=$(cat ${{ github.workspace }}/nuxeo-tools-support-priv/testresults.txt)
          if [ -n $ticketsResults ];then
            matrix=$( echo "$ticketsResults"|jq -R 'capture("(?<targets>@here) :(?<alert>.*?): <(?<url>[^ ]+)> (?<title>.*) :[^w]+ (?<duration>.*)")' | jq -sc )
            echo "matrix=$matrix" >> $GITHUB_OUTPUT
          fi

      - name: No tickets
        if: ${{ steps.get-tickets.outputs.ticketsResults == '' }}
        run: echo "No tickets are approaching breach"

  notification:
    needs: prepare-matrix
    runs-on: ubuntu-latest
    if: ${{ needs.prepare-matrix.outputs.ticketsResults != '' }}
    strategy:
      matrix:
        tickets: ${{ fromJson(needs.prepare-matrix.outputs.matrix) }}
    steps:
      - name: Sending Tickets at Risk Notifications
        uses: slackapi/slack-github-action@e28cf165c92ffef168d23c5c9000cffc8a25e117 # v1.24.0
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        with:
          channel-id: "${{ github.event.inputs.slack_channel }}"
          payload: |
            {
              "text": "Notification on <${{ matrix.tickets.url }}|${{ matrix.tickets.title }}> breach status",
              "blocks": [
                {
                  "type": "context",
                  "elements": [
                    {
                      "type": "image",
                      "image_url": "https://avatars.githubusercontent.com/u/460607?s=48&v=4",
                      "alt_text": "Nuxeo Support"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "${{ matrix.tickets.targets }} **Nuxeo Suport Breachwatcher**"
                    }
                  ]
                },
                {
                  "type": "divider"
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": ":${{ matrix.tickets.alert }}: Ticket <${{ matrix.tickets.url }}|${{ matrix.tickets.title }}> approaching breach in ${{ matrix.tickets.duration }} !"
                  }
                }
              ]
            }

  notify-on-error:
    runs-on: ubuntu-latest
    needs: [prepare-matrix]
    if: ${{ failure() }}
    steps:
      - name: Slack Notification
        uses: slackapi/slack-github-action@e28cf165c92ffef168d23c5c9000cffc8a25e117
        with:
          channel-id: "C06AG4TUBRB"
          slack-message: "Breatchwatcher job failed! <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|Click here>"
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
