on:
    workflow_dispatch

jobs:
  prepare-matrix:
    runs-on: ubuntu-latest
    outputs:
        matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: prepare matrix
        id: set-matrix
        run: |
          notifsList="testresults.txt"
          notifs_length=$(cat testresults.txt | wc -l)
            echo "matrix=$(cat testresults.txt | sed -n 's/^@here :alert: <\([^|]*\)|\([^>]*\)> \(.*\) :alert: \[\([^]]*\)\]/{"url":"\1","issue":"\2","duration":"\4"}/p' | jq -cRs 'split("\n")[:-1]' )" >> $GITHUB_OUTPUT          
  create-matrix:
    needs: prepare-matrix
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tickets: ${{ fromJson(needs.prepare-matrix.outputs.matrix) }}
    steps:
      - run: |
          echo "Dynamic value: ${{ needs.prepare-matrix.outputs.matrix }}"

  
  
